kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    #avp.kubernetes.io/path: "kv/secret/apps/appdes1 | base64encode"
    avp.kubernetes.io/path: "kv/data/secret/deploy/src/devops/appdes1"
type: Opaque
stringData:
  #username: <username-vault-key | base64encode>
  #password: <password-vault-key | base64encode>
  username: <username-vault-key>
  password: <password-vault-key>
## vault kv put kv/secret/apps/appdes1 username-vault-key="appdes1" password-vault-key="gopadres"

## De: https://argocd-vault-plugin.readthedocs.io/en/stable/backends/
## Note: For KV-V2 backends, the path needs to be specified as
## ${vault-kvv2-backend-path}/data/{path-to-secret} where vault-kvv2-backend-path
## is the path to the KV-V2 backend (usually just secret) and path-to-secret is the
## path to the secret in Vault.
## 6
